function ClusterIcon(a,c){a.getMarkerClusterer().extend(ClusterIcon,google.maps.OverlayView);this.cluster_=a;this.className_=a.getMarkerClusterer().getClusterClass();this.classNameSelected_=a.getMarkerClusterer().getClusterClassSelected();this.styles_=c;this.sums_=this.div_=this.center_=null;this.visible_=!1;this.setMap(a.getMap())}
ClusterIcon.prototype.onAdd=function(){var a=this,c,b;this.div_=document.createElement("div");this.visible_&&(this.div_.className=this.className_,this.show());this.getPanes().overlayMouseTarget.appendChild(this.div_);this.boundsChangedListener_=google.maps.event.addListener(this.getMap(),"bounds_changed",function(){b=c});google.maps.event.addDomListener(this.div_,"mousedown",function(){c=!0;b=!1});google.maps.event.addDomListener(this.div_,"click",function(d){c=!1;if(!b){var e,f=a.cluster_.getMarkerClusterer();
google.maps.event.trigger(f,"click",a.cluster_,a.div_);google.maps.event.trigger(f,"clusterclick",a.cluster_,a.div_);var g=!1;f.getZoomOnClick()||a.cluster_.getSize()>f.getClusterSizeToZoom()?(e=f.maxZoom_,null!==e&&f.getMap().getZoom()<e?f.getMap().setZoom(f.getMap().getZoom()+1):g=!0):g=!0;g&&a.div_?a.cluster_.getMarkerClusterer().setSelectedCluster(a.div_.id):a.cluster_.getMarkerClusterer().setSelectedCluster(void 0);d.cancelBubble=!0;d.stop&&d.stop();d.stopPropagation&&d.stopPropagation();d.preventDefault?
d.preventDefault():d.returnValue=!1}});google.maps.event.addDomListener(this.div_,"mouseover",function(){var b=a.cluster_.getMarkerClusterer();google.maps.event.trigger(b,"mouseover",a.cluster_)});google.maps.event.addDomListener(this.div_,"mouseout",function(){var b=a.cluster_.getMarkerClusterer();google.maps.event.trigger(b,"mouseout",a.cluster_)})};
ClusterIcon.prototype.onRemove=function(){this.div_&&this.div_.parentNode&&(this.hide(),google.maps.event.removeListener(this.boundsChangedListener_),google.maps.event.clearInstanceListeners(this.div_),this.div_.parentNode.removeChild(this.div_),this.div_=null)};ClusterIcon.prototype.draw=function(){if(this.visible_){var a=this.getPosFromLatLng_(this.center_);this.div_.style.top=a.y+"px";this.div_.style.left=a.x+"px"}};
ClusterIcon.prototype.hide=function(){this.div_&&(this.div_.style.display="none");this.visible_=!1};
ClusterIcon.prototype.show=function(){if(this.div_){var a=this.getPosFromLatLng_(this.center_);this.div_.style.cssText=this.createCss(a);this.div_.id="clusterDiv_"+a.x+"_"+a.y;this.div_.id===this.cluster_.getMarkerClusterer().getSelectedCluster()?this.div_.className=this.classNameSelected_:this.div_.className=this.className_;a=this.cluster_.getMarkerClusterer().getTranscludedLabel();this.div_.innerHTML=a?a.replace("{{interpolated}}",this.sums_.text):"<div style='position: absolute;top: "+this.anchorText_[0]+
"px;left: "+this.anchorText_[1]+"px;color: "+this.textColor_+";font-size: "+this.textSize_+"px;font-family: "+this.fontFamily_+";font-weight: "+this.fontWeight_+";font-style: "+this.fontStyle_+";text-decoration: "+this.textDecoration_+";text-align: center;width: "+this.width_+"px;line-height:"+this.height_+"px;'>"+(this.cluster_.hideLabel_?" ":this.sums_.text)+"</div>";this.div_.title="undefined"===typeof this.sums_.title||""===this.sums_.title?this.cluster_.getMarkerClusterer().getTitle():this.sums_.title;
this.div_.style.display=""}this.visible_=!0};
ClusterIcon.prototype.useStyle=function(a){this.sums_=a;a=Math.max(0,a.index-1);a=Math.min(this.styles_.length-1,a);a=this.styles_[a];this.url_=a.url;this.height_=a.height;this.width_=a.width;this.anchorText_=a.anchorText||[0,0];this.anchorIcon_=a.anchorIcon||[parseInt(this.height_/2,10),parseInt(this.width_/2,10)];this.textColor_=a.textColor||"black";this.textSize_=a.textSize||11;this.textDecoration_=a.textDecoration||"none";this.fontWeight_=a.fontWeight||"bold";this.fontStyle_=a.fontStyle||"normal";
this.fontFamily_=a.fontFamily||"Arial,sans-serif";this.backgroundPosition_=a.backgroundPosition||"0 0"};ClusterIcon.prototype.setCenter=function(a){this.center_=a};ClusterIcon.prototype.createCss=function(a){var c=[];c.push("cursor: pointer;");c.push("position: absolute; top: "+a.y+"px; left: "+a.x+"px;");c.push("width: "+this.width_+"px; height: "+this.height_+"px;");return c.join("")};
ClusterIcon.prototype.getPosFromLatLng_=function(a){a=this.getProjection().fromLatLngToDivPixel(a);a.x-=this.anchorIcon_[1];a.y-=this.anchorIcon_[0];a.x=parseInt(a.x,10);a.y=parseInt(a.y,10);return a};
function Cluster(a){this.markerClusterer_=a;this.map_=a.getMap();this.gridSize_=a.getGridSize();this.minClusterSize_=a.getMinimumClusterSize();this.averageCenter_=a.getAverageCenter();this.hideLabel_=a.getHideLabel();this.markers_=[];this.bounds_=this.center_=null;this.clusterIcon_=new ClusterIcon(this,a.getStyles())}Cluster.prototype.getSize=function(){return this.markers_.length};Cluster.prototype.getMarkers=function(){return this.markers_};Cluster.prototype.getCenter=function(){return this.center_};
Cluster.prototype.getMap=function(){return this.map_};Cluster.prototype.getMarkerClusterer=function(){return this.markerClusterer_};Cluster.prototype.getBounds=function(){var a,c=new google.maps.LatLngBounds(this.center_,this.center_),b=this.getMarkers();for(a=0;a<b.length;a++)c.extend(b[a].getPosition());return c};Cluster.prototype.remove=function(){this.clusterIcon_.setMap(null);this.markers_=[];delete this.markers_};
Cluster.prototype.addMarker=function(a){var c,b;if(this.isMarkerAlreadyAdded_(a))return!1;this.center_?this.averageCenter_&&(b=this.markers_.length+1,c=(this.center_.lat()*(b-1)+a.getPosition().lat())/b,b=(this.center_.lng()*(b-1)+a.getPosition().lng())/b,this.center_=new google.maps.LatLng(c,b),this.calculateBounds_()):(this.center_=a.getPosition(),this.calculateBounds_());a.isAdded=!0;this.markers_.push(a);c=this.markers_.length;b=this.markerClusterer_.getMaxZoom();if(null!==b&&this.map_.getZoom()>
b)a.getMap()!==this.map_&&a.setMap(this.map_);else if(c<this.minClusterSize_)a.getMap()!==this.map_&&a.setMap(this.map_);else if(c===this.minClusterSize_)for(a=0;a<c;a++)this.markers_[a].setMap(null);else a.setMap(null);this.updateIcon_();return!0};Cluster.prototype.isMarkerInClusterBounds=function(a){return this.bounds_.contains(a.getPosition())};Cluster.prototype.calculateBounds_=function(){var a=new google.maps.LatLngBounds(this.center_,this.center_);this.bounds_=this.markerClusterer_.getExtendedBounds(a)};
Cluster.prototype.updateIcon_=function(){var a=this.markers_.length,c=this.markerClusterer_.getMaxZoom();null!==c&&this.map_.getZoom()>c?this.clusterIcon_.hide():a<this.minClusterSize_?this.clusterIcon_.hide():(a=this.markerClusterer_.getStyles().length,a=this.markerClusterer_.getCalculator()(this.markers_,a),this.clusterIcon_.setCenter(this.center_),this.clusterIcon_.useStyle(a),this.clusterIcon_.show())};
Cluster.prototype.isMarkerAlreadyAdded_=function(a){var c;if(this.markers_.indexOf)return-1!==this.markers_.indexOf(a);for(c=0;c<this.markers_.length;c++)if(a===this.markers_[c])return!0;return!1};
function MarkerClusterer(a,c,b){this.extend(MarkerClusterer,google.maps.OverlayView);c=c||[];b=b||{};this.markers_=[];this.clusters_=[];this.listeners_=[];this.activeMap_=null;this.ready_=!1;this.gridSize_=b.gridSize||60;this.minClusterSize_=b.minimumClusterSize||2;this.maxZoom_=b.maxZoom||null;this.styles_=b.styles||[];this.title_=b.title||"";this.zoomOnClick_=!0;void 0!==b.zoomOnClick&&(this.zoomOnClick_=b.zoomOnClick);this.clusterSizeToZoom_=0;void 0!==b.clusterSizeToZoom&&(this.clusterSizeToZoom_=
b.clusterSizeToZoom);this.averageCenter_=!1;void 0!==b.averageCenter&&(this.averageCenter_=b.averageCenter);this.ignoreHidden_=!1;void 0!==b.ignoreHidden&&(this.ignoreHidden_=b.ignoreHidden);this.enableRetinaIcons_=!1;void 0!==b.enableRetinaIcons&&(this.enableRetinaIcons_=b.enableRetinaIcons);this.hideLabel_=!1;void 0!==b.hideLabel&&(this.hideLabel_=b.hideLabel);this.imagePath_=b.imagePath||MarkerClusterer.IMAGE_PATH;this.imageExtension_=b.imageExtension||MarkerClusterer.IMAGE_EXTENSION;this.imageSizes_=
b.imageSizes||MarkerClusterer.IMAGE_SIZES;this.calculator_=b.calculator||MarkerClusterer.CALCULATOR;this.batchSize_=b.batchSize||MarkerClusterer.BATCH_SIZE;this.batchSizeIE_=b.batchSizeIE||MarkerClusterer.BATCH_SIZE_IE;this.clusterClass_=b.clusterClass||"cluster";this.clusterClassSelected_=b.clusterClassSelected||"cluster active";-1!==navigator.userAgent.toLowerCase().indexOf("msie")&&(this.batchSize_=this.batchSizeIE_);this.setupStyles_();this.addMarkers(c,!0);this.setMap(a)}
MarkerClusterer.prototype.onAdd=function(){var a=this;this.activeMap_=this.getMap();this.ready_=!0;this.repaint();this.listeners_=[google.maps.event.addListener(this.getMap(),"zoom_changed",function(){a.resetViewport_(!1);this.getZoom()!==(this.get("minZoom")||0)&&this.getZoom()!==this.get("maxZoom")||google.maps.event.trigger(this,"idle")}),google.maps.event.addListener(this.getMap(),"idle",function(){a.redraw_()})]};
MarkerClusterer.prototype.onRemove=function(){var a;for(a=0;a<this.markers_.length;a++)this.markers_[a].getMap()!==this.activeMap_&&this.markers_[a].setMap(this.activeMap_);for(a=0;a<this.clusters_.length;a++)this.clusters_[a].remove();this.clusters_=[];for(a=0;a<this.listeners_.length;a++)google.maps.event.removeListener(this.listeners_[a]);this.listeners_=[];this.activeMap_=null;this.ready_=!1};MarkerClusterer.prototype.draw=function(){};
MarkerClusterer.prototype.setupStyles_=function(){var a,c;if(!(0<this.styles_.length))for(a=0;a<this.imageSizes_.length;a++)c=this.imageSizes_[a],this.styles_.push({url:this.imagePath_+(a+1)+"."+this.imageExtension_,height:c,width:c})};MarkerClusterer.prototype.fitMapToMarkers=function(){var a,c=this.getMarkers(),b=new google.maps.LatLngBounds;for(a=0;a<c.length;a++)b.extend(c[a].getPosition());this.getMap().fitBounds(b)};MarkerClusterer.prototype.getGridSize=function(){return this.gridSize_};
MarkerClusterer.prototype.setGridSize=function(a){this.gridSize_=a};MarkerClusterer.prototype.getMinimumClusterSize=function(){return this.minClusterSize_};MarkerClusterer.prototype.setMinimumClusterSize=function(a){this.minClusterSize_=a};MarkerClusterer.prototype.getMaxZoom=function(){return this.maxZoom_};MarkerClusterer.prototype.setMaxZoom=function(a){this.maxZoom_=a};MarkerClusterer.prototype.getStyles=function(){return this.styles_};
MarkerClusterer.prototype.setStyles=function(a){this.styles_=a};MarkerClusterer.prototype.getTitle=function(){return this.title_};MarkerClusterer.prototype.setTitle=function(a){this.title_=a};MarkerClusterer.prototype.getZoomOnClick=function(){return this.zoomOnClick_};MarkerClusterer.prototype.setZoomOnClick=function(a){this.zoomOnClick_=a};MarkerClusterer.prototype.getClusterSizeToZoom=function(){return this.clusterSizeToZoom_};
MarkerClusterer.prototype.setClusterSizeToZoom=function(a){this.clusterSizeToZoom_=a};MarkerClusterer.prototype.getAverageCenter=function(){return this.averageCenter_};MarkerClusterer.prototype.setAverageCenter=function(a){this.averageCenter_=a};MarkerClusterer.prototype.getIgnoreHidden=function(){return this.ignoreHidden_};MarkerClusterer.prototype.setIgnoreHidden=function(a){this.ignoreHidden_=a};MarkerClusterer.prototype.getEnableRetinaIcons=function(){return this.enableRetinaIcons_};
MarkerClusterer.prototype.setEnableRetinaIcons=function(a){this.enableRetinaIcons_=a};MarkerClusterer.prototype.getImageExtension=function(){return this.imageExtension_};MarkerClusterer.prototype.setImageExtension=function(a){this.imageExtension_=a};MarkerClusterer.prototype.getImagePath=function(){return this.imagePath_};MarkerClusterer.prototype.setImagePath=function(a){this.imagePath_=a};MarkerClusterer.prototype.getImageSizes=function(){return this.imageSizes_};
MarkerClusterer.prototype.setImageSizes=function(a){this.imageSizes_=a};MarkerClusterer.prototype.getCalculator=function(){return this.calculator_};MarkerClusterer.prototype.setCalculator=function(a){this.calculator_=a};MarkerClusterer.prototype.setHideLabel=function(a){this.hideLabel_=a};MarkerClusterer.prototype.getHideLabel=function(){return this.hideLabel_};MarkerClusterer.prototype.getBatchSizeIE=function(){return this.batchSizeIE_};
MarkerClusterer.prototype.setBatchSizeIE=function(a){this.batchSizeIE_=a};MarkerClusterer.prototype.getClusterClass=function(){return this.clusterClass_};MarkerClusterer.prototype.setClusterClass=function(a){this.clusterClass_=a};MarkerClusterer.prototype.getClusterClassSelected=function(){return this.clusterClassSelected_};MarkerClusterer.prototype.setClusterClassSelected=function(a){this.clusterClassSelected_=a};MarkerClusterer.prototype.getSelectedCluster=function(){return this.selectedCluster_};
MarkerClusterer.prototype.setSelectedCluster=function(a){this.selectedCluster_=a};MarkerClusterer.prototype.getMarkers=function(){return this.markers_};MarkerClusterer.prototype.getTotalMarkers=function(){return this.markers_.length};MarkerClusterer.prototype.getClusters=function(){return this.clusters_};MarkerClusterer.prototype.getTotalClusters=function(){return this.clusters_.length};MarkerClusterer.prototype.addMarker=function(a,c){this.pushMarkerTo_(a);c||this.redraw_()};
MarkerClusterer.prototype.addMarkers=function(a,c){for(var b in a)a.hasOwnProperty(b)&&this.pushMarkerTo_(a[b]);c||this.redraw_()};MarkerClusterer.prototype.pushMarkerTo_=function(a){if(a.getDraggable()){var c=this;google.maps.event.addListener(a,"dragend",function(){c.ready_&&(this.isAdded=!1,c.repaint())})}a.isAdded=!1;this.markers_.push(a)};MarkerClusterer.prototype.removeMarker=function(a,c,b){a=this.removeMarker_(a,!b);!c&&a&&this.repaint();return a};
MarkerClusterer.prototype.removeMarkers=function(a,c,b){var d,e=!1,f=!b;for(b=0;b<a.length;b++)d=this.removeMarker_(a[b],f),e=e||d;!c&&e&&this.repaint();return e};MarkerClusterer.prototype.removeMarker_=function(a,c){var b,d=-1;if(this.markers_.indexOf)d=this.markers_.indexOf(a);else for(b=0;b<this.markers_.length;b++)if(a===this.markers_[b]){d=b;break}if(-1===d)return!1;c&&a.setMap(null);this.markers_.splice(d,1);return!0};
MarkerClusterer.prototype.clearMarkers=function(){this.resetViewport_(!0);this.markers_=[]};MarkerClusterer.prototype.repaint=function(){var a=this.clusters_.slice();this.clusters_=[];this.resetViewport_(!1);this.redraw_();setTimeout(function(){var c;for(c=0;c<a.length;c++)a[c].remove()},0)};
MarkerClusterer.prototype.getExtendedBounds=function(a){var c=this.getProjection(),b=new google.maps.LatLng(a.getNorthEast().lat(),a.getNorthEast().lng()),d=new google.maps.LatLng(a.getSouthWest().lat(),a.getSouthWest().lng()),b=c.fromLatLngToDivPixel(b);b.x+=this.gridSize_;b.y-=this.gridSize_;d=c.fromLatLngToDivPixel(d);d.x-=this.gridSize_;d.y+=this.gridSize_;b=c.fromDivPixelToLatLng(b);c=c.fromDivPixelToLatLng(d);a.extend(b);a.extend(c);return a};MarkerClusterer.prototype.redraw_=function(){this.createClusters_(0)};
MarkerClusterer.prototype.resetViewport_=function(a){var c,b;for(c=0;c<this.clusters_.length;c++)this.clusters_[c].remove();this.clusters_=[];for(c=0;c<this.markers_.length;c++)b=this.markers_[c],b.isAdded=!1,a&&b.setMap(null)};
MarkerClusterer.prototype.distanceBetweenPoints_=function(a,c){var b=(c.lat()-a.lat())*Math.PI/180,d=(c.lng()-a.lng())*Math.PI/180,b=Math.sin(b/2)*Math.sin(b/2)+Math.cos(a.lat()*Math.PI/180)*Math.cos(c.lat()*Math.PI/180)*Math.sin(d/2)*Math.sin(d/2);return 12742*Math.atan2(Math.sqrt(b),Math.sqrt(1-b))};MarkerClusterer.prototype.isMarkerInBounds_=function(a,c){return c.contains(a.getPosition())};
MarkerClusterer.prototype.addToClosestCluster_=function(a){var c,b,d,e=4E4,f=null;for(c=0;c<this.clusters_.length;c++)if(d=this.clusters_[c],b=d.getCenter())b=this.distanceBetweenPoints_(b,a.getPosition()),b<e&&(e=b,f=d);f&&f.isMarkerInClusterBounds(a)?f.addMarker(a):(d=new Cluster(this),d.addMarker(a),this.clusters_.push(d))};
MarkerClusterer.prototype.createClusters_=function(a){var c,b,d=this;if(this.ready_){0===a&&(google.maps.event.trigger(this,"clusteringbegin",this),"undefined"!==typeof this.timerRefStatic&&(clearTimeout(this.timerRefStatic),delete this.timerRefStatic));b=3<this.getMap().getZoom()?new google.maps.LatLngBounds(this.getMap().getBounds().getSouthWest(),this.getMap().getBounds().getNorthEast()):new google.maps.LatLngBounds(new google.maps.LatLng(85.02070771743472,-178.48388434375),new google.maps.LatLng(-85.08136444384544,
178.00048865625));b=this.getExtendedBounds(b);for(var e=Math.min(a+this.batchSize_,this.markers_.length);a<e;a++)c=this.markers_[a],!c.isAdded&&this.isMarkerInBounds_(c,b)&&(!this.ignoreHidden_||this.ignoreHidden_&&c.getVisible())&&this.addToClosestCluster_(c);e<this.markers_.length?this.timerRefStatic=setTimeout(function(){d.createClusters_(e)},0):(delete this.timerRefStatic,google.maps.event.trigger(this,"clusteringend",this))}};
MarkerClusterer.prototype.extend=function(a,c){return function(a){for(var c in a.prototype)this.prototype[c]=a.prototype[c];return this}.apply(a,[c])};MarkerClusterer.CALCULATOR=function(a,c){for(var b=0,d=a.length.toString(),e=d;0!==e;)e=parseInt(e/10,10),b++;b=Math.min(b,c);return{text:d,index:b,title:""}};MarkerClusterer.prototype.setTranscludedLabel=function(a){this.transcludedLabel=a};MarkerClusterer.prototype.getTranscludedLabel=function(){return this.transcludedLabel};
MarkerClusterer.BATCH_SIZE=2E3;MarkerClusterer.BATCH_SIZE_IE=500;MarkerClusterer.IMAGE_PATH="http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclustererplus/images/m";MarkerClusterer.IMAGE_EXTENSION="png";MarkerClusterer.IMAGE_SIZES=[53,56,66,78,90];"function"!==typeof String.prototype.trim&&(String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")});
"undefined"!==typeof exports?("undefined"!==typeof module&&module.exports&&(exports=module.exports=MarkerClusterer),exports._=_):root._=_;
